repos:
  - repo: local
    hooks:
      - id: rustfmt-check
        name: rustfmt (check)
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
        verbose: true
      - id: clippy-check
        name: clippy (check)
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        verbose: true
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.2
    hooks:
      - id: pylint
